import { IMAGEPATH } from './ImagePath';

export const FLATLLIST = [
  {
    id: 1,
    mainContainerImage: IMAGEPATH.SilverImage,
    Silver: 'Silver',
    textdo: '$88,966.43',
    ss: '-2.45%',
    nagtive: true
  },
  {
    id: 2,
    mainContainerImage: IMAGEPATH.godImage,
    Silver: 'Gold',
    textdo: '$58,000',
    ss: '+5.80%',
    nagtive: false
  },
  {
    id: 3,
    mainContainerImage: IMAGEPATH.SilverImage,
    Silver: 'Silver',
    textdo: '$88,966.43',
    ss: '-2.45%',
    nagtive: true
  },

];

export const FLATLLISTDATA = [
  {
    id: 1,
    mainContainerImage: IMAGEPATH.SilverImage,
    Silver: 'Silver',
    textdo: '$88,966.43',
    ss: '-2.45%',
  },
  {
    id: 2,
    mainContainerImage: IMAGEPATH.godImage,
    Silver: 'Gold',
    textdo: '$58,000',
    ss: '+5.80%',
  },
  {
    id: 3,
    mainContainerImage: IMAGEPATH.AEDImage,
    Silver: 'AED',
    textdo: '$88,966.43',
    ss: '-2.45%',
  },
  {
    id: 4,
    mainContainerImage: IMAGEPATH.usdImage,
    Silver: 'USD',
    textdo: '$58,000',
    ss: '+5.80%',
  },

]


export const AllOrderData = [
  {
    id: 1, godImageImage: IMAGEPATH.godImage,
    Gold: 'Gold',
    byy: 'Byy | 23 Jun 2022',
    leftTopA: IMAGEPATH.leftTopA,
    ounce: '100 Ounce',
    puls: '+2.45%',
    buy: 'Avg buy price',
    aed: 'AED 2000.36',
    qty: "Executed Qty",
    soropya:'100 Ounce ',
    oder: 'Order Types',
    mak: 'Market',
    nagtive : false,
  },
  {
    id: 2, godImageImage: IMAGEPATH.SilverImage,
    Gold: 'Silver',
    byy: 'Buy    I   23 Jun 2022',
    leftTopA: IMAGEPATH.daonImage,
    ounce: '100 Ounce',
    puls: '+2.45%',
    buy: 'Avg buy price',
    aed: 'AED 2000.36',
    qty: "Executed Qty",
    soropya:'100 Ounce ',
    oder: 'Order Types',
    mak: 'Sell Limit',
    nagtive : true,
  },
  {
    id: 3, godImageImage: IMAGEPATH.AEDImage,
    Gold: 'Gold',
    byy: 'Byy | 23 Jun 2022',
    leftTopA: IMAGEPATH.leftTopA,
    ounce: '100 Ounce',
    puls: '+2.45%',
    buy: 'Avg buy price',
    aed: 'AED 2000.36',
    qty: "Executed Qty",
    soropya:'300 ',
    oder: 'Order Types',
    mak: 'Market',
    nagtive : false,
  },
  {
    id: 4, godImageImage: IMAGEPATH.usdImage,
    Gold: 'Gold',
    byy: 'Byy | 23 Jun 2022',
    leftTopA: IMAGEPATH.leftTopA,
    ounce: '100 Ounce',
    puls: '+2.45%',
    buy: 'Avg buy price',
    aed: 'AED 2000.36',
    qty: "Executed Qty",
    soropya:'100 ',
    oder: 'Order Types',
    mak: 'Market',
    nagtive : false,
  }
];


export const PendingOrders = [
  {
    id: 1, godImageImage: IMAGEPATH.godImage,
    Gold: 'Gold',
    byy: 'Byy | 23 Jun 2022',
    leftTopA: IMAGEPATH.leftTopA,
    ounce: '100 Ounce',
    puls: '+2.45%',
    buy: 'Avg buy price',
    aed: 'AED 2000.36',
    qty: "Executed Qty",
    soropya:'100 Ounce ',
    oder: 'Order Types',
    mak: 'Market',
    cancelImage:IMAGEPATH.cancel,
    cancel:'cancel',
    UpdateImage: IMAGEPATH.Update,
    Update:'Update',
    nagtive : false,
  },
  {
    id: 2, godImageImage: IMAGEPATH.SilverImage,
    Gold: 'Silver',
    byy: 'Buy    I   23 Jun 2022',
    leftTopA: IMAGEPATH.daonImage,
    ounce: '100 Ounce',
    puls: '+2.45%',
    buy: 'Avg buy price',
    aed: 'AED 2000.36',
    qty: "Executed Qty",
    soropya:'100 Ounce ',
    oder: 'Order Types',
    mak: 'Sell Limit',
    cancelImage:IMAGEPATH.cancel,
    cancel:'cancel',
    UpdateImage: IMAGEPATH.Update,
    Update:'Update',
    nagtive : true,
  },
  {
    id: 3, godImageImage: IMAGEPATH.AEDImage,
    Gold: 'AED',
    byy: 'Byy | 23 Jun 2022',
    leftTopA: IMAGEPATH.leftTopA,
    ounce: '100 Ounce',
    puls: '+2.45%',
    buy: 'Avg buy price',
    aed: 'AED 2000.36',
    qty: "Executed Qty",
    soropya:'300 ',
    oder: 'Order Types',
    mak: 'Market',
    cancelImage:IMAGEPATH.cancel,
    cancel:'cancel',
    UpdateImage: IMAGEPATH.Update,
    Update:'Update',
    nagtive : false,
  },
  {
    id: 4, godImageImage: IMAGEPATH.usdImage,
    Gold: 'Gold',
    byy: 'Byy | 23 Jun 2022',
    leftTopA: IMAGEPATH.leftTopA,
    ounce: '100 Ounce',
    puls: '+2.45%',
    buy: 'Avg buy price',
    aed: 'AED 2000.36',
    qty: "Executed Qty",
    soropya:'100 ',
    oder: 'Order Types',
    mak: 'Market',
    cancelImage:IMAGEPATH.cancel,
    cancel:'cancel',
    UpdateImage: IMAGEPATH.Update,
    Update:'Update',
    nagtive : false,
  },
];


export const TransferHistoryData = [
  {
    id:1, UserGilImageConatiner : IMAGEPATH.UserGilImage,
    AngelaText:'Angela Smith',
    dateJun:'23 Jun 2022',
    OunceContainer:'100 Ounce',
    Assettype:'Asset type',
    Gold:'Gold',
    marketvalue : 'market value',
    Doler:'$ 28.3495.00',
  },
  {
    id:2, UserGilImageConatiner : IMAGEPATH.RoseHope,
    AngelaText:'Rose Hope',
    dateJun:'23 Jun 2022',
    OunceContainer:'100 Ounce',
    Assettype:'Asset type',
    Gold:'Gold',
    marketvalue : 'market value',
    Doler:'$ 28.3495.00',
  },
  {
    id:3, UserGilImageConatiner : IMAGEPATH.AngelaSmith,
    AngelaText:'Angela Smith',
    dateJun:'23 Jun 2022',
    OunceContainer:'100 Ounce',
    Assettype:'Asset type',
    Gold:'Gold',
    marketvalue : 'market value',
    Doler:'$ 28.3495.00',
  },
  {
    id:4, UserGilImageConatiner : IMAGEPATH.Samantha1,
    AngelaText:'Samantha',
    dateJun:'23 Jun 2022',
    OunceContainer:'100 Ounce',
    Assettype:'Asset type',
    Gold:'Gold',
    marketvalue : 'market value',
    Doler:'$ 28.3495.00',
  }
]


