export const IMAGEPATH = {
    order: require('../Image/order.png'),
    Email: require('../Image/Email.png'),
    AEDImage: require('../Image/AED.png'),
    usdImage: require('../Image/usd.png'),
    lockImage: require('../Image/lock.png'),
    mainLogo: require('../Image/MGFLOGO.png'),
    GifatImage: require('../Image/Gifat.png'),
    userLogo: require('../Image/userLogo.png'),
    godImage: require('../Image/godImage.png'),
    password: require('../Image/password.png'),
    SilverImage: require('../Image/Silver.png'),
    DateImage: require('../Image/DateImage.png'),
    userImage: require('../Image/userImage.png'),
    GroupImage: require('../Image/Group7885.png'),
    SignUpLogo: require('../Image/SignUpLogo.png'),
    PhoneImage: require('../Image/PhoneImage.png'),
    passwordShow: require('../Image/passwordShow.png'),
    notificationImage: require('../Image/notification.png'),
    rightManu: require('../Image/rightManu.png'),
    SamanthaImage: require('../Image/Samantha.png'),
    userIcons: require('../Image/userIcons.png'),
    leftImage: require('../Image/leftImage.png'),
    Transfer: require('../Image/Transfer.png'),
    Settings: require('../Image/Settings.png'),
    BillingDetails: require('../Image/BillingDetails.png'),
    Notifications: require('../Image/Notifications.png'),
    LogoutImage: require('../Image/LogoutImage.png'),
    CallImage: require('../Image/CallImage.png'),
    cameraImage: require('../Image/camera.png'),
    hidePassword: require('../Image/hidePassword.png'),
    UserGilImage:require('../Image/UserGil.png'),
    networkLogo:require('../Image/networkLogo.png'),
    leftTopA:require('../Image/leftTopA.png'),
    daonImage:require('../Image/daonImage.png'),
    cancel:require('../Image/cancel.png'),
    Update:require('../Image/Update.png'),
    mainesImage:require('../Image/mainesImage.png'),
    pulsImage:require('../Image/pulsImage.png'),
    modalRogImage:require('../Image/modalRogImage.png'),
    rightModal:require('../Image/rightModal.png')
};
